# This workflow will build the .NET project, run npm and webpack, and upload the artifact
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Production (.NET)
on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: ./.github/actions/build
      with:
        environment: 'prod'
    